name: deploy to droplet

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to droplet via ssh
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            echo "== Start at $(date) =="

            cd /root

            if [ ! -d "CNS_Bot" ]; then
              echo "== Cloning repo at $(date) =="
              git clone git@github.com:ENIGMA-RL/CNS_Bot.git
            fi

            cd CNS_Bot

            echo "== Pulling latest changes at $(date) =="
            git pull origin main

            echo "== Installing dependencies at $(date) =="
            npm install
            echo "== Dependencies installed at $(date) =="

            echo "== Writing .env file at $(date) =="
            echo "TOKEN=${{ secrets.TOKEN }}" > .env
            echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
            echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
            echo "PREFIX=${{ secrets.PREFIX }}" >> .env

            echo "== Restarting bot via PM2 at $(date) =="
            pm2 delete CNS_Bot || true
            pm2 start npm --name CNS_Bot -- run start
            pm2 save

            echo "== Deployment finished at $(date) =="
