name: deploy to droplet

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to droplet via ssh
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /root

            if [ ! -d "CNS_Bot" ]; then
              git clone git@github.com:ENIGMA-RL/CNS_Bot.git
            fi

            cd CNS_Bot
            git pull origin main
            npm install

            echo "TOKEN=${{ secrets.TOKEN }}" > .env
            echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
            echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
            echo "PREFIX=${{ secrets.PREFIX }}" >> .env

            # Stop the current running process
            pkill -f 'node src/index.js' || true

            # Start the new version
            nohup npm run start > output.log 2>&1 &
