name: deploy to droplet

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to droplet via ssh
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /root

            if [ ! -d "CNS_Bot" ]; then
              git clone git@github.com:ENIGMA-RL/CNS_Bot.git
            fi

            cd CNS_Bot
            git pull origin main
            npm install

            echo "TOKEN=${{ secrets.TOKEN }}" > .env
            echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
            echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
            echo "PREFIX=${{ secrets.PREFIX }}" >> .env

            # Stop old bot process if running
            pm2 delete CNS_Bot || true

            # Start bot with PM2
            pm2 start npm --name CNS_Bot -- run start

            # Save process list
            pm2 save
